name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ysiner/ssh-app:${{ github.sha }} .
        docker tag ysiner/ssh-app:${{ github.sha }} ysiner/ssh-app:latest
        docker push ysiner/ssh-app:${{ github.sha }}
        docker push ysiner/ssh-app:latest

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up KUBECONFIG from GitHub Secrets
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/ssh-app ssh-app=ysiner/ssh-app:latest -n default
        kubectl rollout restart deployment/ssh-app -n default